spring:

  application:
    name: hm-search-service

  cloud:
    stream:
      bindings:
        candidate-created:
          destination: live.hiring-master
          group: search-service-candidate-created
        candidate-updated:
          destination: live.hiring-master
          group: search-service-candidate-updated
        candidate-data-deleted:
          destination: live.hiring-master
          group: search-service-candidate-data-deleted
      rabbit:
        bindings:
          candidate-created:
            consumer:
              bindingRoutingKey: candidate-created
              autoBindDlq: true
          candidate-updated:
            consumer:
              bindingRoutingKey: candidate-updated
              autoBindDlq: true
          candidate-data-deleted:
            consumer:
              bindingRoutingKey: candidate-data-deleted
              autoBindDlq: true

  rabbitmq:
    addresses: amqps://ljugmhry:4eLoNvWxjeNf80-YgfBBvwN1XcaUZ4Pk@rattlesnake.rmq.cloudamqp.com/ljugmhry
